// Generated by CoffeeScript 1.6.3
(function() {
  var expect;

  mocha.ui('bdd');

  mocha.reporter('html');

  chai.should();

  expect = chai.expect;

  describe("#define", function() {
    return it("defines module", function() {
      var module;
      require.define({
        'a': function(exports, require, module) {
          return exports.test = 'test';
        }
      });
      module = require('a');
      return module.test.should.be.equal('test');
    });
  });

  describe("#require", function() {
    it("throws error if module is not defined", function() {
      return expect(function() {
        return require('does not exist');
      }).to["throw"](/not found/);
    });
    it("does not evaluat module until it is required", function() {
      var spy;
      spy = sinon.spy();
      require.define({
        "b": function(exports, require, module) {
          return spy();
        }
      });
      spy.called.should.not.be.ok;
      require("b");
      return spy.calledOnce.should.be.ok;
    });
    return it("evauates only once", function() {
      var spy;
      spy = sinon.spy();
      require.define({
        "c": function(exports, require, module) {
          return spy();
        }
      });
      require("c");
      spy.calledOnce.should.be.ok;
      require("c");
      return spy.calledOnce.should.be.ok;
    });
  });

}).call(this);
